travis:
  secure:
    BINSTAR_TOKEN: USPlWn8hBFQGWBD99Bwf6DEshH3DRyGTr3HfPaptwQb6iav/RNaKYhMPpMff4iGmwB36pOUUhrXReyFnTF4a4rikSX2Vat5ZgHstoeop+XgTwZbEoUA3AoqEQZqGm5lupG8GFDYhKlkzB3tiYciyRyzfzKOkUjkVJnAXszeaq/t7jKt7F3yyLCd0fXKqWIuSX8kjJogTaBGazLsWLMB00VaHm2BkCScO53oEXCO8TbUvYeg1xA5NzzRhEi/7kgDS5S1NBIeSQjmhbvLndORZsDhAPWe0qpCuMtTLp9nB8z2pajGZ3+cTRp0+tiAx83hs3GSarW4D1zLF1sC5NSLCO0iftzdMMGotAh0IzM+9jeBV1XKNOZw9t8R/rQwlRUDgREbcZQ7PltG8PMUU31KhCEzF5ano9u4Go22nIZPsv71b29ZUCVVqM+Cde1+nvza9TTf/8o55Nr0tLi+/jKft7Xorx/r/0ZhsaP/0uZbya9HvApuf1+83hQmtvBGh9qXHmv3e+hHYDFiaFUo0wXDqGdxBfUTQPiA15/ymZOmS9Ue+YMhkyEsWw3OCHmYCnqMBc9Qat2rJxl65s5tKXcvYwgfdv6ezbSfGfhohrTeQLB17dJxIrcYcebzTUBAaJNtgBoNKMANLSoTThcwhwznSr5se1Yhg/d8uehgxPWf8/SQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
